spring:
  profiles:
    active: h2
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true
logging:
  level:
    org.springframework.security: DEBUG

security:
  jwt:
    secret-key: 42f87806eb5e695882afe118505621537eb1ca450d6a074496028209502c3f51
    access-exp-delay: 90000000
    refresh-exp-delay: 7200000
    prefix: Bearer
    auth-header: Authorization